// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqy6VjkoMODAYB4muk4sgt8SFDpIPCr0',
    appId: '1:487621717466:web:e7d9450b9b6ea032a9a4e3',
    messagingSenderId: '487621717466',
    projectId: 'vaner-f83ef',
    authDomain: 'vaner-f83ef.firebaseapp.com',
    storageBucket: 'vaner-f83ef.firebasestorage.app',
    measurementId: 'G-XYT725K1HK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw9jYFPqnVfd6dAW8VqDWkzfJvENgOU9s',
    appId: '1:487621717466:android:e22aa3269cfb587aa9a4e3',
    messagingSenderId: '487621717466',
    projectId: 'vaner-f83ef',
    storageBucket: 'vaner-f83ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpIDlEkjez8IS5H_c4LG19zre7Ju0iHVg',
    appId: '1:487621717466:ios:72d51fbba549a739a9a4e3',
    messagingSenderId: '487621717466',
    projectId: 'vaner-f83ef',
    storageBucket: 'vaner-f83ef.firebasestorage.app',
    iosClientId: '487621717466-9gf8r31cf34nvhuso9oovg68lr26r9gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpIDlEkjez8IS5H_c4LG19zre7Ju0iHVg',
    appId: '1:487621717466:ios:72d51fbba549a739a9a4e3',
    messagingSenderId: '487621717466',
    projectId: 'vaner-f83ef',
    storageBucket: 'vaner-f83ef.firebasestorage.app',
    iosClientId: '487621717466-9gf8r31cf34nvhuso9oovg68lr26r9gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.vaner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqy6VjkoMODAYB4muk4sgt8SFDpIPCr0',
    appId: '1:487621717466:web:4c5edcb7cd0976c6a9a4e3',
    messagingSenderId: '487621717466',
    projectId: 'vaner-f83ef',
    authDomain: 'vaner-f83ef.firebaseapp.com',
    storageBucket: 'vaner-f83ef.firebasestorage.app',
    measurementId: 'G-K71FJBC7EF',
  );

}